name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - 'apps/drizzle-service/package.json'
      - 'packages/**'
      - 'apps/drizzle-service/src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/drizzle-service/package.json'
      - 'packages/**'
      - 'apps/drizzle-service/src/**'

jobs:
  test:
    name: Testing SQLite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
          
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Configure Postgres
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: |
          echo "Postgres is ready for testing"
          echo "DATABASE_URL=$DATABASE_URL" > packages/test/.env
          
      - name: Run build
        run: pnpm build:lib
        
      - name: Push database schema
        run: |
            pnpm db:push:pg
            pnpm db:push:sqlite

      - name: Run tests
        run: pnpm test
